// tmp_prefix_sum_global.comp
#version 450
layout(local_size_x = 256) in;

layout(push_constant) uniform PushConstants {
    uint num_elements;
} pc;

layout(binding = 1) buffer Data { uint data[]; };
layout(binding = 2) buffer BlockSums { uint block_sums[]; };

void main() {
    uint gidx = gl_GlobalInvocationID.x;
    uint wgid = gl_WorkGroupID.x;
    
    if (wgid > 0 && gidx < pc.num_elements) {
        data[gidx] += block_sums[wgid - 1];
    }
}
